
name: Testing

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Running unit and snapshot tests
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2

    - name: Test
      run: npm test
